import { type Brick, type Collection } from "./types";

export const initialCollections: Collection[] = [
  {
    id: "travel",
    name: "Travel Phrases",
    iconName: "Plane",
    tags: ["Essentials", "Survival"],
    color: "secondary",
    description:
      "Manage your curated sets of vocabulary and grammar blocks. Organize your journey brick by brick.",
    progress: 65,
  },
  {
    id: "business",
    name: "Business English",
    iconName: "Briefcase",
    tags: ["Formal", "Meetings", "Negotiation"],
    color: "primary",
    description:
      "Navigate professional conversations, email communications, and key corporate terminology with ease.",
    progress: 20,
  },
  {
    id: "food",
    name: "Food & Dining",
    iconName: "Utensils",
    tags: ["Restaurant", "Cafe"],
    color: "tertiary",
    description:
      "Master ordering, dining interactions, and identifying culinary ingredients across cultures.",
    progress: 95,
  },
  {
    id: "routine",
    name: "Daily Routine",
    iconName: "Clock",
    tags: ["Habits", "Time"],
    color: "secondary",
    description:
      "Learn to describe daily activities, schedule obligations, and conversational time anchors.",
    progress: 40,
  },
];

export const initialBricks: Brick[] = [
  // Travel Phrases
  {
    id: "t1",
    nativeText: "Where is the library?",
    targetText: "¿Dónde está la biblioteca?",
    pronunciation: "/ˈdon.de esˈta la βi.βljoˈte.ka/",
    status: "reviewing",
    tags: ["Beginner", "Travel", "Greeting"],
    collectionId: "travel",
    pronunciationScore: 92,
    accuracyScore: 78,
    createdAt: "2026-07-10T12:00:00Z",
  },
  {
    id: "t2",
    nativeText: "Where is the bathroom?",
    targetText: "¿Dónde está el baño?",
    pronunciation: "/ˈdon.de esˈta el ˈβa.ɲo/",
    status: "mastered",
    tags: ["Question", "Essential", "Travel"],
    collectionId: "travel",
    pronunciationScore: 98,
    accuracyScore: 95,
    createdAt: "2026-07-11T12:00:00Z",
  },
  {
    id: "t3",
    nativeText: "I would like to order...",
    targetText: "Me gustaría pedir...",
    pronunciation: "/me ɣus.taˈɾi.a peˈðiɾ/",
    status: "reviewing",
    tags: ["Dining", "Travel"],
    collectionId: "travel",
    createdAt: "2026-07-12T12:00:00Z",
  },
  {
    id: "t4",
    nativeText: "Have a nice trip!",
    targetText: "¡Buen viaje!",
    pronunciation: "/bwen ˈbja.xe/",
    status: "new",
    tags: ["Greeting", "Travel"],
    collectionId: "travel",
    createdAt: "2026-07-13T12:00:00Z",
  },
  {
    id: "t5",
    nativeText: "How much does this cost?",
    targetText: "¿Cuánto cuesta esto?",
    pronunciation: "/ˈkwan.to ˈkwes.ta ˈes.to/",
    status: "reviewing",
    tags: ["Shopping", "Travel"],
    collectionId: "travel",
    createdAt: "2026-07-14T12:00:00Z",
  },
  {
    id: "t6",
    nativeText: "Sorry for the delay",
    targetText: "Perdón por el retraso",
    pronunciation: "/peɾˈðon poɾ el reˈtɾa.so/",
    status: "mastered",
    tags: ["Polite", "Travel"],
    collectionId: "travel",
    createdAt: "2026-07-15T12:00:00Z",
  },
  {
    id: "t7",
    nativeText: "The bill, please",
    targetText: "La cuenta, por favor",
    pronunciation: "/la ˈkwen.ta poɾ faˈβoɾ/",
    status: "new",
    tags: ["Dining", "Travel"],
    collectionId: "travel",
    createdAt: "2026-07-16T12:00:00Z",
  },

  // Food & Dining Collection
  {
    id: "f1",
    nativeText: "Could I have the bill, please?",
    targetText: "¿Podría traerme la cuenta, por favor?",
    pronunciation: "/poˈðɾi.a tɾaˈeɾ.me la ˈkwen.ta poɾ faˈβoɾ/",
    status: "mastered",
    tags: ["Polite Request", "Restaurant", "Food"],
    collectionId: "food",
    createdAt: "2026-07-01T12:00:00Z",
  },
  {
    id: "f2",
    nativeText: "I'd like an oat milk latte.",
    targetText: "Me gustaría un café con leche de avena.",
    pronunciation: "/me ɣus.taˈɾi.a un kaˈfe kon ˈle.tʃe ðe aˈβe.na/",
    status: "reviewing",
    tags: ["Ordering", "Cafe", "Food"],
    collectionId: "food",
    createdAt: "2026-07-02T12:00:00Z",
  },

  // Business English
  {
    id: "b1",
    nativeText: "Let us schedule a meeting.",
    targetText: "Programemos una reunión.",
    pronunciation: "/pɾo.ɣe.me.mos ˈu.na reu̯ˈnjon/",
    status: "new",
    tags: ["Meetings", "Business"],
    collectionId: "business",
    createdAt: "2026-07-03T12:00:00Z",
  },
  {
    id: "b2",
    nativeText: "It is a pleasure doing business with you.",
    targetText: "Es un placer hacer negocios con usted.",
    pronunciation: "/es un plaˈceɾ aˈceɾ neˈɣo.cjos kon usˈteð/",
    status: "reviewing",
    tags: ["Formal", "Business"],
    collectionId: "business",
    createdAt: "2026-07-04T12:00:00Z",
  },

  // Daily Routine
  {
    id: "r1",
    nativeText: "I wake up at seven in the morning.",
    targetText: "Me despierto a las siete de la mañana.",
    pronunciation: "/me ðesˈpjeɾ.to a las ˈsje.te ðe la maˈɲa.na/",
    status: "mastered",
    tags: ["Habits", "Time", "Routine"],
    collectionId: "routine",
    createdAt: "2026-07-05T12:00:00Z",
  },
];

// Curated public stream for Discover tab
export const discoverBricks: Brick[] = [
  {
    id: "d1",
    nativeText: "Could I have the bill, please?",
    targetText: "¿Podría traerme la cuenta, por favor?",
    pronunciation: "/poˈðɾi.a tɾaˈeɾ.me la ˈkwen.ta poɾ faˈβoɾ/",
    status: "new",
    tags: ["Travel", "Dining"],
    collectionId: "discover",
    createdAt: "2026-07-01T10:00:00Z",
  },
  {
    id: "d2",
    nativeText: "How do I get to the station?",
    targetText: "¿Cómo llego a la estación?",
    pronunciation: "/ˈko.mo ˈʝe.ɣo a la es.taˈθjon/",
    status: "new",
    tags: ["Essential", "Commute"],
    collectionId: "discover",
    createdAt: "2026-07-02T10:00:00Z",
  },
  {
    id: "d3",
    nativeText: "I'd like an oat milk latte.",
    targetText: "Me gustaría un café con leche de avena.",
    pronunciation: "/me ɣus.taˈɾi.a un kaˈfe kon ˈle.tʃe ðe aˈβe.na/",
    status: "new",
    tags: ["Food", "Daily"],
    collectionId: "discover",
    createdAt: "2026-07-03T10:00:00Z",
  },
  {
    id: "d4",
    nativeText: "Is there a pharmacy nearby?",
    targetText: "¿Hay alguna farmacia cerca?",
    pronunciation: "/ai̯ alˈɣu.na faɾˈma.θja ˈθeɾ.ka/",
    status: "new",
    tags: ["Emergency", "Useful"],
    collectionId: "discover",
    createdAt: "2026-07-04T10:00:00Z",
  },
  {
    id: "d5",
    nativeText: "Can you recommend a good local restaurant?",
    targetText: "¿Me puede recomendar un buen restaurante local?",
    pronunciation: "/me ˈpwe.ðe re.ko.menˈdaɾ un bwen res.tau̯ˈɾan.te loˈkal/",
    status: "new",
    tags: ["Food", "Dining"],
    collectionId: "discover",
    createdAt: "2026-07-05T10:00:00Z",
  },
  {
    id: "d6",
    nativeText: "Where is the nearest tourist office?",
    targetText: "¿Dónde está la oficina de turismo más cercana?",
    pronunciation: "/ˈdon.de esˈta la o.fiˈθi.na ðe tuˈɾiz.mo mas θeɾˈka.na/",
    status: "new",
    tags: ["Travel", "Essentials"],
    collectionId: "discover",
    createdAt: "2026-07-06T10:00:00Z",
  },
];
